version: '3.9'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    depends_on:
      - app
    container_name: ${APP_NAME}_nginx
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
      - ./_docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - db
    container_name: ${APP_NAME}_php
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    container_name: '${APP_NAME}_adminer'
    depends_on:
      - db
  db:
    image: postgres:15.3
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql
    environment:
          - POSTGRES_DB=${DB_DATABASE}
          - POSTGRES_USER=${DB_USERNAME}
          - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    container_name: ${APP_NAME}_postgres